services:
  # Backend service
  - type: web
    name: barbapp-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile.prod
    dockerContext: backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: barbapp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: barbapp-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: barbapp-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: barbapp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: barbapp-db
          property: password
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    healthCheckPath: /api/healthcheck

  # Nginx service (serving frontend and routing to backend)
  - type: web
    name: barbapp-nginx
    runtime: docker
    dockerfilePath: nginx/Dockerfile.prod
    dockerContext: nginx
    envVars:
      - key: BACKEND_URL
        value: https://barbapp-backend.onrender.com

# Database
databases:
  - name: barbapp-db
    databaseName: barbapp
    user: barbapp_user
