services:
  # Backend service
  - type: web
    name: barbapp-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerContext: ./backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: barbapp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: barbapp-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: barbapp-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: barbapp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: barbapp-db
          property: password
    healthCheckPath: /api/healthcheck

  # Frontend service (includes Nginx)
  - type: web
    name: barbapp-frontend
    runtime: docker
    dockerfilePath: ./frontend/barbapp/Dockerfile
    dockerContext: ./frontend/barbapp
    envVars:
      - key: PORT
        value: 80
      - key: REACT_APP_API_URL
        value: https://barbapp-backend.onrender.com

# Database
databases:
  - name: barbapp-db
    databaseName: barbapp
    user: barbapp_user
