# Generated by Django 5.0.7 on 2024-08-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
