# Generated by Django 5.0.7 on 2024-08-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_image_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('independent', 'Independent'), ('beauty_shop', 'Beauty Shop'), ('beauty_supplier', 'Beauty Supplier')], default='independent', max_length=20),
        ),
    ]
