# Generated by Django 5.0.7 on 2024-08-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_shop_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shop_type',
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('independent', 'Independent'), ('beauty_shop', 'Beauty Shop'), ('beauty_supplier', 'Beauty Supplier')], default='independent', max_length=20),
        ),
    ]
