# Generated by Django 5.0.7 on 2024-08-16 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_shop_shop_type_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='ShopClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='shops.shop')),
            ],
        ),
    ]
