# Generated by Django 5.0.7 on 2024-08-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_shop_opening_hours_shopclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
