# Generated by Django 5.0.7 on 2024-08-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shop_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
    ]
