# Generated by Django 5.0.7 on 2024-08-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_shop_opening_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopClosure',
        ),
    ]
