# Generated by Django 5.0.7 on 2024-08-18 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_appointment_shop_alter_appointment_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='shop',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
