# Generated by Django 5.0.7 on 2024-08-18 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_alter_appointment_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shop'),
        ),
    ]
