# Generated by Django 5.0.7 on 2024-08-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_alter_appointment_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
