# Build stage
FROM node:18.17.0-alpine as build

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

# Production stage
FROM node:18.17.0-alpine

WORKDIR /app

COPY --from=build /app/build ./build
COPY --from=build /app/package.json ./package.json

RUN yarn global add serve

CMD ["serve", "-s", "build", "-l", "3000"]

EXPOSE 3000