# Use an official node image as a parent image
FROM node:18.17.0-alpine as build

# Set the working directory
WORKDIR /app

# Copy the package.json and install dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install

# Copy the rest of the application code
COPY . .

# Set environment variable to disable host check
ENV WDS_SOCKET_HOST=0.0.0.0
ENV WDS_SOCKET_PORT=3000
ENV CHOKIDAR_USEPOLLING=true

# Expose port 3000
EXPOSE 3000

# Start Nginx server
CMD ["yarn", "start"]
