# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the custom Nginx configuration
COPY nginx.conf.prod /etc/nginx/nginx.conf

# Copy the built React app from the build stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose the port that Nginx will serve on
EXPOSE 80

# Run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
