name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r backend/requirements.txt

            - name: Set environment variables
              run: |
                  echo "PYTHONPATH=$(pwd)/backend" >> $GITHUB_ENV
                  echo "DJANGO_SETTINGS_MODULE=barbapp.settings" >> $GITHUB_ENV
                  echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
                  echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
                  echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
                  echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
                  echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
                  echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV

            - name: Run migrations
              run: |
                  python backend/manage.py migrate

            - name: Run tests
              run: |
                  pytest
