name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f backend/requirements.txt ]; then
                    pip install -r backend/requirements.txt
                  else
                    echo "backend/requirements.txt not found. Skipping pip install."
                  fi

            - name: Run tests
              run: |
                  pytest
