name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Debug Python Path
              run: |
                  echo $PYTHONPATH
                    python -c "import sys; print(sys.path)"
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f backend/requirements.txt ]; then
                    pip install -r backend/requirements.txt
                  else
                    echo "backend/requirements.txt not found. Skipping pip install."
                  fi

            - name: Set environment variables
              run: |
                  echo "PYTHONPATH=$(pwd)/backend" >> $GITHUB_ENV
                  echo "DJANGO_SETTINGS_MODULE=backend.barbapp.settings" >> $GITHUB_ENV

            - name: Run tests
              run: |
                  pytest
