name: Update Dependencies

on:
    schedule:
        - cron: "0 0 * * 1" # Every Monday at midnight

jobs:
    update-dependencies:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9"

            - name: Install pip-tools
              run: pip install pip-tools

            - name: Compile requirements
              run: pip-compile requirements.in

            - name: Commit and push if there are changes
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "actions@github.com"
                  git add requirements.txt
                  git diff-index --quiet HEAD || git commit -m "Update requirements.txt"
                  git push
