name: Update Dependencies

on:
    schedule:
        - cron: "0 0 * * 1" # Every Monday at midnight

jobs:
    update-dependencies:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]

        steps:
            - name: Checkout code
              uses: actions/checkout@4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install pip-tools
              run: pip install pip-tools

            - name: Compile requirements
              run: |
                  if [ -f requirements.in ]; then
                    pip-compile requirements.in
                  else
                    echo "requirements.in not found. Skipping pip-compile."
                  fi

            - name: Commit and push if there are changes
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "actions@github.com"
                  git add requirements.txt
                  git diff-index --quiet HEAD || git commit -m "Update requirements.txt"
                  git push
